const fs = require('fs');
const path = require('path');

// Safe file writer to create folders and write contents
function writeFile(targetPath, contentLines) {
  const fullPath = path.join(__dirname, targetPath);
  const dirName = path.dirname(fullPath);
  
  if (!fs.existsSync(dirName)) {
    fs.mkdirSync(dirName, { recursive: true });
  }
  
  fs.writeFileSync(fullPath, contentLines.join('\n'), 'utf8');
  console.log('Successfully wrote file to: ' + targetPath);
}

// 1. app/admin/_layout.tsx (Crimson Red Bottom Tab Bar & Red Header)
const adminLayout = [
  "import React from 'react';",
  "import { Tabs } from 'expo-router';",
  "import { MaterialCommunityIcons } from '@expo/vector-icons';",
  "",
  "export default function AdminLayout() {",
  "  return (",
  "    <Tabs ",
  "      screenOptions={{ ",
  "        tabBarActiveTintColor: '#FFFFFF', ",
  "        tabBarInactiveTintColor: '#FFCDD2',",
  "        tabBarStyle: { ",
  "          backgroundColor: '#D32F2F', ",
  "          height: 60, ",
  "          paddingBottom: 6 ",
  "        },",
  "        headerStyle: { ",
  "          backgroundColor: '#D32F2F' ",
  "        },",
  "        headerTintColor: '#FFFFFF',",
  "        headerTitleStyle: { ",
  "          fontWeight: 'bold' ",
  "        }",
  "      }}",
  "    >",
  "      <Tabs.Screen ",
  "        name='index' ",
  "        options={{ ",
  "          title: 'Dashboard', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='view-dashboard' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='employees' ",
  "        options={{ ",
  "          title: 'Employees', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='account-group' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='leaves' ",
  "        options={{ ",
  "          title: 'Leaves', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='calendar-check' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='reports' ",
  "        options={{ ",
  "          title: 'Reports', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='file-chart' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='settings' ",
  "        options={{ ",
  "          title: 'Settings', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='cog' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='notices' ",
  "        options={{ ",
  "          title: 'Notices', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='bullhorn' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='notifications' ",
  "        options={{ ",
  "          href: null,",
  "          title: 'Notifications'",
  "        }} ",
  "      />",
  "    </Tabs>",
  "  );",
  "}"
];

// 2. app/employee/_layout.tsx (Crimson Red Bottom Tab Bar - Hidden extra tabs)
const employeeLayout = [
  "import React from 'react';",
  "import { Tabs } from 'expo-router';",
  "import { MaterialCommunityIcons } from '@expo/vector-icons';",
  "",
  "export default function EmployeeLayout() {",
  "  return (",
  "    <Tabs ",
  "      screenOptions={{ ",
  "        tabBarActiveTintColor: '#FFFFFF', ",
  "        tabBarInactiveTintColor: '#FFCDD2',",
  "        tabBarStyle: { ",
  "          backgroundColor: '#D32F2F', ",
  "          height: 60, ",
  "          paddingBottom: 6 ",
  "        },",
  "        headerStyle: { ",
  "          backgroundColor: '#D32F2F' ",
  "        },",
  "        headerTintColor: '#FFFFFF',",
  "        headerTitleStyle: { ",
  "          fontWeight: 'bold' ",
  "        }",
  "      }}",
  "    >",
  "      <Tabs.Screen ",
  "        name='index' ",
  "        options={{ ",
  "          title: 'Home', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='home' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='attendance' ",
  "        options={{ ",
  "          title: 'Attendance', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='calendar-clock' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='leaves' ",
  "        options={{ ",
  "          title: 'Leaves', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='calendar-edit' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='salary' ",
  "        options={{ ",
  "          title: 'Salary', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='cash-multiple' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='profile' ",
  "        options={{ ",
  "          title: 'Profile', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='account' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='notices' ",
  "        options={{ ",
  "          title: 'Notices', ",
  "          tabBarIcon: ({ color }) => (",
  "            <MaterialCommunityIcons ",
  "              name='bullhorn' ",
  "              size={24} ",
  "              color={color} ",
  "            />",
  "          )",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='notifications' ",
  "        options={{ ",
  "          href: null,",
  "          title: 'Notifications'",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='loans' ",
  "        options={{ ",
  "          href: null,",
  "          title: 'Loans'",
  "        }} ",
  "      />",
  "      <Tabs.Screen ",
  "        name='advances' ",
  "        options={{ ",
  "          href: null,",
  "          title: 'Advances'",
  "        }} ",
  "      />",
  "    </Tabs>",
  "  );",
  "}"
];

// 3. app/admin/index.tsx (Red and White Premium Admin Dashboard)
const adminDashboard = [
  "import React, { useState, useEffect } from 'react';",
  "import { View, Text, StyleSheet, ScrollView, TouchableOpacity, RefreshControl } from 
'react-native';",
  "import { Card, Button, Surface, Provider, MD3LightTheme } from 'react-native-paper';",
  "import { MaterialCommunityIcons } from '@expo/vector-icons';",
  "import { useAuth } from '../../src/context/AuthContext';",
  "import { api } from '../../src/services/api';",
  "import { useRouter } from 'expo-router';",
  "",
  "export default function AdminDashboard() {",
  "  const { user, token } = useAuth();",
  "  const router = useRouter();",
  "  const [refreshing, setRefreshing] = useState(false);",
  "  const [stats, setStats] = useState({ present: 0, pendingLeaves: 0, totalStaff: 0 });",
  "",
  "  const loadStats = async () => {",
  "    if (!token) return;",
  "    try {",
  "      const users = await api.getUsers(token);",
  "      const leaves = await api.getAllLeaves(token, 'pending');",
  "      ",
  "      const d = new Date();",
  "      const utc = d.getTime() + (d.getTimezoneOffset() * 60000);",
  "      const ist = new Date(utc + (3600000 * 5.5));",
  "      const y = ist.getFullYear();",
  "      const m = String(ist.getMonth() + 1).padStart(2, '0');",
  "      const day = String(ist.getDate()).padStart(2, '0');",
  "      const todayStr = y + '-' + m + '-' + day;",
  "      ",
  "      const attendance = await api.getAllAttendance(token, todayStr);",
  "      const presentCount = attendance.filter(",
  "        (a) => a.status === 'present' || a.status === 'half-day'",
  "      ).length;",
  "",
  "      setStats({",
  "        present: presentCount,",
  "        pendingLeaves: leaves.length,",
  "        totalStaff: users.filter((u) => u.role === 'employee').length,",
  "      });",
  "    } catch (e) {",
  "      console.error('Failed to load admin stats:', e);",
  "    }",
  "  };",
  "",
  "  useEffect(() => {",
  "    loadStats();",
  "  }, []);",
  "",
  "  const onRefresh = async () => {",
  "    setRefreshing(true);",
  "    await loadStats();",
  "    setRefreshing(false);",
  "  };",
  "",
  "  const redTheme = {",
  "    ...MD3LightTheme,",
  "    colors: {",
  "      ...MD3LightTheme.colors,",
  "      primary: '#D32F2F',",
  "    },",
  "  };",
  "",
  "  return (",
  "    <Provider theme={redTheme}>",
  "      <View style={styles.screen}>",
  "        <Surface style={styles.headerSurface}>",
  "          <View style={styles.headerRow}>",
  "            <View>",
  "              <Text style={styles.headerTitle}>Kalanjiyam Stores</Text>",
  "              <Text style={styles.headerSub}>Admin Portal • {user?.name}</Text>",
  "            </View>",
  "            <TouchableOpacity ",
  "              onPress={() => router.push('/admin/notifications')} ",
  "              style={styles.bellButton}",
  "            >",
  "              <MaterialCommunityIcons name='bell-ring' size={24} color='#fff' />",
  "            </TouchableOpacity>",
  "          </View>",
  "        </Surface>",
  "",
  "        <ScrollView",
  "          style={styles.content}",
  "          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}",
  "        >",
  "          <View style={styles.metricsGrid}>",
  "            <View style={[styles.metricCard, { borderLeftColor: '#4CAF50' }]}>",
  "              <MaterialCommunityIcons name='account-check' size={28} color='#4CAF50' />",
  "              <Text style={styles.metricNum}>{stats.present}</Text>",
  "              <Text style={styles.metricLabel}>Today Present</Text>",
  "            </View>",
  "            <View style={[styles.metricCard, { borderLeftColor: '#FF9800' }]}>",
  "              <MaterialCommunityIcons name='calendar-alert' size={28} color='#FF9800' />",
  "              <Text style={styles.metricNum}>{stats.pendingLeaves}</Text>",
  "              <Text style={styles.metricLabel}>Pending Leaves</Text>",
  "            </View>",
  "            <View style={[styles.metricCard, { borderLeftColor: '#D32F2F' }]}>",
  "              <MaterialCommunityIcons name='account-group' size={28} color='#D32F2F' />",
  "              <Text style={styles.metricNum}>{stats.totalStaff}</Text>",
  "              <Text style={styles.metricLabel}>Total Staff</Text>",
  "            </View>",
  "          </View>",
  "",
  "          <Card style={styles.card}>",
  "            <Card.Title title='Quick Actions' titleStyle={{ fontWeight: 'bold' }} />",
  "            <Card.Content style={styles.btnRow}>",
  "              <Button ",
  "                mode='contained' ",
  "                buttonColor='#D32F2F' ",
  "                style={styles.actionBtn}",
  "                onPress={() => router.push('/admin/employees')}",
  "                icon='account-plus'",
  "              >",
  "                Add Staff",
  "              </Button>",
  "              <Button ",
  "                mode='contained' ",
  "                buttonColor='#D32F2F' ",
  "                style={styles.actionBtn}",
  "                onPress={() => router.push('/admin/settings')}",
  "                icon='bullhorn'",
  "              >",
  "                Broadcast Notice",
  "              </Button>",
  "            </Card.Content>",
  "          </Card>",
  "",
  "          <Card style={styles.card}>",
  "            <Card.Title title='System Status' titleStyle={{ fontWeight: 'bold' }} />",
  "            <Card.Content>",
  "              <View style={styles.infoRow}>",
  "                <MaterialCommunityIcons name='check-circle' size={18} color='#4CAF50' />",
  "                <Text style={styles.infoText}>API Live Server connection: ONLINE</Text>",
  "              </View>",
  "              <View style={styles.infoRow}>",
  "                <MaterialCommunityIcons name='shield-check' size={18} color='#1976D2' />",
  "                <Text style={styles.infoText}>Biometric token synchronization active.</Text>",
  "              </View>",
  "            </Card.Content>",
  "          </Card>",
  "          <View style={{ height: 40 }} />",
  "        </ScrollView>",
  "      </View>",
  "    </Provider>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  screen: { flex: 1, backgroundColor: '#f5f5f5' },",
  "  headerSurface: { padding: 20, backgroundColor: '#D32F2F', elevation: 4, borderBottomLeftRadius: 
16, borderBottomRightRadius: 16 },",
  "  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },",
  "  headerTitle: { fontSize: 22, fontWeight: 'bold', color: '#fff' },",
  "  headerSub: { fontSize: 13, color: '#FFCDD2', marginTop: 2 },",
  "  bellButton: { padding: 4 },",
  "  content: { flex: 1, padding: 12 },",
  "  metricsGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, marginBottom: 12 
},",
  "  metricCard: { flex: 1, backgroundColor: '#fff', borderRadius: 12, padding: 14, alignItems: 
'center', elevation: 2, borderLeftWidth: 4 },",
  "  metricNum: { fontSize: 20, fontWeight: 'bold', color: '#333', marginTop: 4 },",
  "  metricLabel: { fontSize: 11, color: '#666', marginTop: 2, textAlign: 'center' },",
  "  card: { marginBottom: 12, backgroundColor: '#fff', elevation: 2 },",
  "  btnRow: { flexDirection: 'row', gap: 8 },",
  "  actionBtn: { flex: 1 },",
  "  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },",
  "  infoText: { fontSize: 13, color: '#555', marginLeft: 10 },",
  "});"
];

// 4. app/employee/index.tsx (Staff Home Screen in Crimson Red & White combo)
const employeeIndex = [
  "import React, { useState, useEffect } from 'react';",
  "import { View, StyleSheet, ScrollView, Alert, RefreshControl, TouchableOpacity } from 
'react-native';",
  "import { Text, Button, Card, Surface, Provider, MD3LightTheme } from 'react-native-paper';",
  "import { useAuth } from '../../src/context/AuthContext';",
  "import { api } from '../../src/services/api';",
  "import { MaterialCommunityIcons } from '@expo/vector-icons';",
  "import { requestLocationPermission, getCurrentLocation, isWithinShowroom } from 
'../../src/utils/location';",
  "import { useRouter } from 'expo-router';",
  "",
  "const getISTDateValues = () => {",
  "  const now = new Date();",
  "  const ist = new Date(now.getTime() + (5.5 * 60 * 60 * 1000));",
  "  const weekDays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 
'Saturday'];",
  "  const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 
'September', 'October', 'November', 'December'];",
  "  const y = ist.getUTCFullYear();",
  "  const m = String(ist.getUTCMonth() + 1).padStart(2, '0');",
  "  const d = String(ist.getUTCDate()).padStart(2, '0');",
  "  return {",
  "    dateString: y + '-' + m + '-' + d,",
  "    monthString: y + '-' + m,",
  "    displayString: weekDays[ist.getUTCDay()] + ' - ' + months[ist.getUTCMonth()] + ' ' + 
ist.getUTCDate() + ', ' + ist.getUTCFullYear()",
  "  };",
  "};",
  "",
  "export default function EmployeeHome() {",
  "  const { user, token } = useAuth();",
  "  const router = useRouter();",
  "  const [loading, setLoading] = useState(false);",
  "  const [todayAttendance, setTodayAttendance] = useState(null);",
  "  const [showroomLocation, setShowroomLocation] = useState(null);",
  "  const [refreshing, setRefreshing] = useState(false);",
  "  const [advances, setAdvances] = useState(null);",
  "  const [loans, setLoans] = useState([]);",
  "",
  "  const loadData = async () => {",
  "    try {",
  "      const settingResponse = await api.getSetting('showroomLocation');",
  "      if (settingResponse && settingResponse.value) {",
  "        setShowroomLocation(settingResponse.value);",
  "      }",
  "",
  "      const istVal = getISTDateValues();",
  "      const attendanceRecords = await api.getMyAttendance(token!);",
  "      const todayRecord = attendanceRecords.find((record) => record.date === 
istVal.dateString);",
  "      setTodayAttendance(todayRecord);",
  "",
  "      const advancesData = await api.getUserAdvances(token!, user!._id, istVal.monthString);",
  "      setAdvances(advancesData);",
  "",
  "      const loansData = await api.getUserLoans(token!, user!._id);",
  "      setLoans(loansData);",
  "    } catch (error) {",
  "      console.error('Failed to load employee data:', error);",
  "    }",
  "  };",
  "",
  "  useEffect(() => {",
  "    loadData();",
  "  }, []);",
  "",
  "  const onRefresh = async () => {",
  "    setRefreshing(true);",
  "    await loadData();",
  "    setRefreshing(false);",
  "  };",
  "",
  "  const handleMarkAttendance = async () => {",
  "    if (!showroomLocation) {",
  "      Alert.alert('Location Not Set', 'Showroom location is not configured. Contact Admin.');",
  "      return;",
  "    }",
  "",
  "    setLoading(true);",
  "    try {",
  "      const hasPermission = await requestLocationPermission();",
  "      if (!hasPermission) {",
  "        Alert.alert('Permission Denied', 'Location permission is required to mark attendance');",
  "        setLoading(false);",
  "        return;",
  "      }",
  "",
  "      const currentLocation = await getCurrentLocation();",
  "      if (!currentLocation) {",
  "        Alert.alert('Error', 'Failed to get your GPS location');",
  "        setLoading(false);",
  "        return;",
  "      }",
  "",
  "      const within = isWithinShowroom(",
  "        currentLocation.latitude,",
  "        currentLocation.longitude,",
  "        showroomLocation.latitude,",
  "        showroomLocation.longitude,",
  "        showroomLocation.radius || 100",
  "      );",
  "",
  "      if (!within) {",
  "        Alert.alert('Location Mismatch', 'You must be inside the showroom to mark attendance');",
  "        setLoading(false);",
  "        return;",
  "      }",
  "",
  "      const response = await api.markAttendance(token!, {",
  "        status: 'present',",
  "        location: currentLocation,",
  "      });",
  "",
  "      Alert.alert('Success', 'Attendance marked as ' + response.status.toUpperCase(), [",
  "        { text: 'OK', onPress: loadData }",
  "      ]);",
  "    } catch (error: any) {",
  "      Alert.alert('Error', error.message || 'Failed to mark attendance');",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  const formatCheckInTime = (timestamp: string) => {",
  "    if (!timestamp) return '';",
  "    return new Date(timestamp).toLocaleTimeString('en-IN', {",
  "      timeZone: 'Asia/Kolkata',",
  "      hour: '2-digit',",
  "      minute: '2-digit',",
  "      hour12: true",
  "    });",
  "  };",
  "",
  "  const redTheme = {",
  "    ...MD3LightTheme,",
  "    colors: {",
  "      ...MD3LightTheme.colors,",
  "      primary: '#D32F2F',",
  "    },",
  "  };",
  "",
  "  return (",
  "    <Provider theme={redTheme}>",
  "      <View style={styles.container}>",
  "        <Surface style={styles.headerSurface}>",
  "          <View style={styles.headerRow}>",
  "            <View>",
  "              <Text style={styles.welcomeText}>Welcome, {user?.name}!</Text>",
  "              <Text style={styles.companyText}>Kalanjiyam Stores • Staff</Text>",
  "              <Text style={styles.dateText}>{getISTDateValues().displayString}</Text>",
  "            </View>",
  "            <TouchableOpacity ",
  "              onPress={() => router.push('/employee/notifications')} ",
  "              style={styles.bellButton}",
  "            >",
  "              <MaterialCommunityIcons name='bell-ring' size={24} color='#fff' />",
  "            </TouchableOpacity>",
  "          </View>",
  "        </Surface>",
  "",
  "        <ScrollView",
  "          contentContainerStyle={styles.contentContainer}",
  "          refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}",
  "        >",
  "          <Card style={styles.card}>",
  "            <Card.Content>",
  "              <View style={styles.statusContainer}>",
  "                <MaterialCommunityIcons",
  "                  name={todayAttendance ? 'check-circle' : 'clock-alert'}",
  "                  size={56}",
  "                  color={todayAttendance ? '#4caf50' : '#666'}",
  "                />",
  "                <Text style={styles.statusTitle}>",
  "                  {todayAttendance ? 'TODAY: ' + todayAttendance.status.toUpperCase() : 
'Attendance Not Marked'}",
  "                </Text>",
  "                {todayAttendance && todayAttendance.checkInTime && (",
  "                  <Text style={styles.timeText}>",
  "                    Check-in: {formatCheckInTime(todayAttendance.checkInTime)}",
  "                  </Text>",
  "                )}",
  "              </View>",
  "",
  "              {!todayAttendance && (",
  "                <Button",
  "                  mode='contained'",
  "                  onPress={handleMarkAttendance}",
  "                  loading={loading}",
  "                  disabled={loading}",
  "                  style={styles.markButton}",
  "                  buttonColor='#D32F2F',",
  "                  icon='check-circle'",
  "                >",
  "                  Mark Attendance",
  "                </Button>",
  "              )}",
  "            </Card.Content>",
  "          </Card>",
  "",
  "          <Card style={styles.card}>",
  "            <Card.Title",
  "              title=\"This Month's Finances\"",
  "              titleStyle={{ fontWeight: 'bold' }}",
  "              left={(props) => <MaterialCommunityIcons {...props} name='cash-multiple' 
color='#D32F2F' />}",
  "            />",
  "            <Card.Content>",
  "              <View style={styles.financeGrid}>",
  "                <View style={[styles.financeCard, { backgroundColor: '#fff3e0' }]}>",
  "                  <MaterialCommunityIcons name='cash-fast' size={28} color='#ff9800' />",
  "                  <Text style={styles.financeAmount}>",
  "                    ₹{advances?.totalThisMonth?.toFixed(0) || '0'}",
  "                  </Text>",
  "                  <Text style={styles.financeLabel}>Advances Taken</Text>",
  "                </View>",
  "",
  "                <View style={[styles.financeCard, { backgroundColor: '#ffebee' }]}>",
  "                  <MaterialCommunityIcons name='bank' size={28} color='#f44336' />",
  "                  {loans.find((l) => l.status === 'active') ? (",
  "                    <>",
  "                      <Text style={styles.financeAmount}>",
  "                        ₹{loans.find((l) => l.status === 'active')?.remainingAmount.toFixed(0)}",
  "                      </Text>",
  "                      <Text style={styles.financeLabel}>Loan Remaining</Text>",
  "                    </>",
  "                  ) : (",
  "                    <>",
  "                      <Text style={styles.financeAmount}>-</Text>",
  "                      <Text style={styles.financeLabel}>No Active Loan</Text>",
  "                    </>",
  "                  )}",
  "                </View>",
  "              </View>",
  "            </Card.Content>",
  "          </Card>",
  "          <View style={{ height: 40 }} />",
  "        </ScrollView>",
  "      </View>",
  "    </Provider>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#f5f5f5' },",
  "  headerSurface: { padding: 20, backgroundColor: '#D32F2F', elevation: 4, borderBottomLeftRadius: 
16, borderBottomRightRadius: 16 },",
  "  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },",
  "  welcomeText: { fontSize: 20, fontWeight: 'bold', color: '#fff' },",
  "  companyText: { color: '#FFCDD2', fontWeight: '600', fontSize: 13, marginTop: 2 },",
  "  dateText: { color: '#FFCDD2', fontSize: 12, marginTop: 4 },",
  "  bellButton: { padding: 4 },",
  "  contentContainer: { padding: 12 },",
  "  card: { marginBottom: 12, backgroundColor: '#fff', elevation: 2 },",
  "  statusContainer: { alignItems: 'center', paddingVertical: 12 },",
  "  statusTitle: { marginTop: 8, fontSize: 16, fontWeight: 'bold', color: '#333' },",
  "  timeText: { marginTop: 4, color: '#666', fontSize: 13 },",
  "  markButton: { marginTop: 12, paddingVertical: 4 },",
  "  financeGrid: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },",
  "  financeCard: { flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', elevation: 1 },",
  "  financeAmount: { fontSize: 18, fontWeight: 'bold', color: '#333', marginTop: 4, marginBottom: 2 
},",
  "  financeLabel: { fontSize: 11, color: '#666', textAlign: 'center' },",
  "});"
];

// 5. app/employee/attendance.tsx (Correct Red & White Attendance History View - Pure JS Date fixes 
173-Year Bug)
const employeeAttendance = [
  "import React, { useState, useEffect } from 'react';",
  "import { View, StyleSheet, ScrollView, RefreshControl, ActivityIndicator } from 'react-native';",
  "import { Text, Card, Divider, Chip, Provider, MD3LightTheme } from 'react-native-paper';",
  "import { useAuth } from '../../src/context/AuthContext';",
  "import { api } from '../../src/services/api';",
  "import { Calendar } from 'react-native-calendars';",
  "import { MaterialCommunityIcons } from '@expo/vector-icons';",
  "",
  "const STATUS_COLORS = {",
  "  present: { key: 'present', color: '#4CAF50' },",
  "  'half-day': { key: 'halfday', color: '#FF9800' },",
  "  absent: { key: 'absent', color: '#F44336' },",
  "  leave: { key: 'leave', color: '#2196F3' },",
  "  holiday: { key: 'holiday', color: '#9C27B0' },",
  "};",
  "",
  "const getISTMonthString = () => {",
  "  const d = new Date();",
  "  const utc = d.getTime() + (d.getTimezoneOffset() * 60000);",
  "  const istDate = new Date(utc + (3600000 * 5.5));",
  "  const year = istDate.getFullYear();",
  "  const month = String(istDate.getMonth() + 1).padStart(2, '0');",
  "  return year + '-' + month;",
  "};",
  "",
  "export default function AttendanceScreen() {",
  "  const { token } = useAuth();",
  "  const [loading, setLoading] = useState(true);",
  "  const [refreshing, setRefreshing] = useState(false);",
  "  const [selectedMonth, setSelectedMonth] = useState(() => getISTMonthString());",
  "  const [attendanceList, setAttendanceList] = useState([]);",
  "  const [markedDates, setMarkedDates] = useState({});",
  "  const [stats, setStats] = useState({ present: 0, halfDay: 0, absent: 0, leave: 0 });",
  "",
  "  const loadAttendance = async () => {",
  "    if (!token) return;",
  "    try {",
  "      const records = await api.getMyAttendance(token, selectedMonth);",
  "      setAttendanceList(records);",
  "",
  "      let p = 0, h = 0, a = 0, l = 0;",
  "      const marks = {};",
  "      ",
  "      for (const rec of records) {",
  "        if (rec.status === 'present') p++;",
  "        else if (rec.status === 'half-day') h++;",
  "        else if (rec.status === 'absent') a++;",
  "        else if (rec.status === 'leave') l++;",
  "",
  "        const info = STATUS_COLORS[rec.status];",
  "        if (info) {",
  "          marks[rec.date] = {",
  "            selected: true,",
  "            selectedColor: info.color,",
  "          };",
  "        }",
  "      }",
  "",
  "      setStats({ present: p, halfDay: h, absent: a, leave: l });",
  "      setMarkedDates(marks);",
  "    } catch (e) {",
  "      console.error('Failed to load attendance logs:', e);",
  "    } finally {",
  "      setLoading(false);",
  "      setRefreshing(false);",
  "    }",
  "  };",
  "",
  "  useEffect(() => {",
  "    loadAttendance();",
  "  }, [selectedMonth]);",
  "",
  "  const onRefresh = () => {",
  "    setRefreshing(true);",
  "    loadAttendance();",
  "  };",
  "",
  "  const formatCheckInTime = (timestamp) => {",
  "    if (!timestamp) return '--:--';",
  "    return new Date(timestamp).toLocaleTimeString('en-IN', {",
  "      timeZone: 'Asia/Kolkata',",
  "      hour: '2-digit',",
  "      minute: '2-digit',",
  "      hour12: true",
  "    });",
  "  };",
  "",
  "  if (loading && !refreshing) {",
  "    return (",
  "      <View style={styles.loading}>",
  "        <ActivityIndicator size='large' color='#D32F2F' />",
  "      </View>",
  "    );",
  "  }",
  "",
  "  const redTheme = {",
  "    ...MD3LightTheme,",
  "    colors: {",
  "      ...MD3LightTheme.colors,",
  "      primary: '#D32F2F',",
  "    },",
  "  };",
  "",
  "  return (",
  "    <Provider theme={redTheme}>",
  "      <ScrollView",
  "        style={styles.screen}",
  "        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} />}",
  "      >",
  "        <Card style={styles.card}>",
  "          <Card.Title title='Attendance History' titleStyle={{ fontWeight: 'bold' }} />",
  "          <Card.Content>",
  "            <View style={styles.legendRow}>",
  "              {Object.entries(STATUS_COLORS).map(([status, info]) => (",
  "                <View key={status} style={styles.legendItem}>",
  "                  <View style={[styles.legendDot, { backgroundColor: info.color }]} />",
  "                  <Text style={styles.legendText}>{status}</Text>",
  "                </View>",
  "              ))}",
  "            </View>",
  "",
  "            <Calendar",
  "              current={selectedMonth + '-01'}",
  "              markedDates={markedDates}",
  "              onMonthChange={(month) => {",
  "                const m = month.year.toString() + '-' + String(month.month).padStart(2, '0');",
  "                setSelectedMonth(m);",
  "              }}",
  "              theme={{",
  "                selectedDayBackgroundColor: '#D32F2F',",
  "                todayTextColor: '#D32F2F',",
  "                arrowColor: '#D32F2F',",
  "              }}",
  "              style={styles.calendar}",
  "            />",
  "          </Card.Content>",
  "        </Card>",
  "",
  "        <View style={styles.statsGrid}>",
  "          <View style={[styles.statBox, { borderLeftColor: '#4CAF50' }]}>",
  "            <Text style={styles.statNum}>{stats.present}</Text>",
  "            <Text style={styles.statLabel}>Present</Text>",
  "          </View>",
  "          <View style={[styles.statBox, { borderLeftColor: '#FF9800' }]}>",
  "            <Text style={styles.statNum}>{stats.halfDay}</Text>",
  "            <Text style={styles.statLabel}>Half-Day</Text>",
  "          </View>",
  "          <View style={[styles.statBox, { borderLeftColor: '#2196F3' }]}>",
  "            <Text style={styles.statNum}>{stats.leave}</Text>",
  "            <Text style={styles.statLabel}>Leave</Text>",
  "          </View>",
  "          <View style={[styles.statBox, { borderLeftColor: '#F44336' }]}>",
  "            <Text style={styles.statNum}>{stats.absent}</Text>",
  "            <Text style={styles.statLabel}>Absent</Text>",
  "          </View>",
  "        </View>",
  "",
  "        <Card style={styles.card}>",
  "          <Card.Title title='Monthly Attendance Log' titleStyle={{ fontWeight: 'bold' }} />",
  "          <Card.Content>",
  "            {attendanceList.length === 0 ? (",
  "              <Text style={styles.emptyText}>No attendance logs for this month</Text>",
  "            ) : (",
  "              attendanceList.map((rec, idx) => (",
  "                <View key={rec._id || idx}>",
  "                  <View style={styles.logRow}>",
  "                    <View>",
  "                      <Text style={styles.logDate}>{rec.date}</Text>",
  "                      {rec.checkInTime && (",
  "                        <Text style={styles.logTime}>Check-In: 
{formatCheckInTime(rec.checkInTime)}</Text>",
  "                      )}",
  "                    </View>",
  "                    <Chip ",
  "                      style={[styles.chip, { backgroundColor: STATUS_COLORS[rec.status]?.color + 
'20' }]}",
  "                      textStyle={{ color: STATUS_COLORS[rec.status]?.color, fontSize: 11, 
fontWeight: 'bold' }}",
  "                    >",
  "                      {rec.status.toUpperCase()}",
  "                    </Chip>",
  "                  </View>",
  "                  {idx < attendanceList.length - 1 && <Divider style={{ marginVertical: 8 }} 
/>}",
  "                </View>",
  "              ))",
  "            )}",
  "          </Card.Content>",
  "        </Card>",
  "        <View style={{ height: 40 }} />",
  "      </ScrollView>",
  "    </Provider>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  screen: { flex: 1, backgroundColor: '#f5f5f5', padding: 12 },",
  "  loading: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 40 },",
  "  card: { marginBottom: 12, backgroundColor: '#fff', elevation: 2 },",
  "  calendar: { borderRadius: 12, marginTop: 8 },",
  "  legendRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 10 },",
  "  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },",
  "  legendDot: { width: 10, height: 10, borderRadius: 5 },",
  "  legendText: { fontSize: 11, color: '#666', textTransform: 'capitalize' },",
  "  statsGrid: { flexDirection: 'row', gap: 6, marginBottom: 12 },",
  "  statBox: { flex: 1, backgroundColor: '#fff', borderRadius: 8, padding: 10, alignItems: 
'center', elevation: 1, borderLeftWidth: 3 },",
  "  statNum: { fontSize: 18, fontWeight: 'bold', color: '#333' },",
  "  statLabel: { fontSize: 10, color: '#666', marginTop: 2 },",
  "  emptyText: { color: '#999', textAlign: 'center', marginVertical: 12 },",
  "  logRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', 
paddingVertical: 4 },",
  "  logDate: { fontSize: 14, fontWeight: '600', color: '#333' },",
  "  logTime: { fontSize: 11, color: '#666', marginTop: 2 },",
  "  chip: { height: 26 },",
  "});"
];

// 6. app/admin/settings.tsx (Correct Settings screen with robust IST Date calculation and Notice 
Broadcast card)
const adminSettings = [
  "import React, { useState, useEffect } from 'react';",
  "import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert, Platform, Keyboard } from 
'react-native';",
  "import { TextInput, Button, Card, Divider, Provider, MD3LightTheme } from 'react-native-paper';",
  "import { MaterialCommunityIcons } from '@expo/vector-icons';",
  "import { useAuth } from '../../src/context/AuthContext';",
  "import { api } from '../../src/services/api';",
  "import * as Location from 'expo-location';",
  "",
  "const getISTDate = () => {",
  "  const d = new Date();",
  "  const utc = d.getTime() + (d.getTimezoneOffset() * 60000);",
  "  return new Date(utc + (3600000 * 5.5));",
  "};",
  "",
  "const getISTDateString = (dateObj) => {",
  "  const d = dateObj || getISTDate();",
  "  return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + 
String(d.getDate()).padStart(2, '0');",
  "};",
  "",
  "export default function SettingsScreen() {",
  "  const { token, logout } = useAuth();",
  "  const [loading, setLoading] = useState(false);",
  "",
  "  const [lat, setLat] = useState('');",
  "  const [lng, setLng] = useState('');",
  "  const [radius, setRadius] = useState('100');",
  "",
  "  const [holidayDate, setHolidayDate] = useState(() => getISTDateString());",
  "  const [holidayReason, setHolidayReason] = useState('');",
  "",
  "  const [currentPassword, setCurrentPassword] = useState('');",
  "  const [newPassword, setNewPassword] = useState('');",
  "  const [confirmPassword, setConfirmPassword] = useState('');",
  "",
  "  const [noticeText, setNoticeText] = useState('');",
  "  const [broadcasting, setBroadcasting] = useState(false);",
  "",
  "  useEffect(() => {",
  "    fetchCurrentLocationSetting();",
  "  }, []);",
  "",
  "  const fetchCurrentLocationSetting = async () => {",
  "    try {",
  "      const response = await api.getSetting('showroomLocation');",
  "      if (response && response.value) {",
  "        setLat(String(response.value.latitude || ''));",
  "        setLng(String(response.value.longitude || ''));",
  "        setRadius(String(response.value.radius || '100'));",
  "      }",
  "    } catch {}",
  "  };",
  "",
  "  const handleUseCurrentLocation = async () => {",
  "    setLoading(true);",
  "    try {",
  "      const { status } = await Location.requestForegroundPermissionsAsync();",
  "      if (status !== 'granted') {",
  "        Alert.alert('Permission Denied', 'Location permission is required');",
  "        return;",
  "      }",
  "      const loc = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High });",
  "      setLat(String(loc.coords.latitude));",
  "      setLng(String(loc.coords.longitude));",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  const handleSaveLocation = async () => {",
  "    if (!lat || !lng || !radius) {",
  "      Alert.alert('Error', 'Please fill in all location fields');",
  "      return;",
  "    }",
  "    setLoading(true);",
  "    try {",
  "      await api.updateSetting(token!, 'showroomLocation', {",
  "        latitude: parseFloat(lat),",
  "        longitude: parseFloat(lng),",
  "        radius: parseFloat(radius),",
  "      });",
  "      Alert.alert('Success', 'Showroom location saved successfully');",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  const handleMarkHoliday = async () => {",
  "    if (!holidayReason) {",
  "      Alert.alert('Error', 'Please enter a reason for the holiday');",
  "      return;",
  "    }",
  "    setLoading(true);",
  "    try {",
  "      await api.markHoliday(token!, holidayDate, holidayReason);",
  "      Alert.alert('Success', 'Holiday marked for all employees on ' + holidayDate);",
  "      setHolidayReason('');",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  const handleUpdatePassword = async () => {",
  "    if (!currentPassword || !newPassword || !confirmPassword) {",
  "      Alert.alert('Error', 'All password fields are required');",
  "      return;",
  "    }",
  "    if (newPassword !== confirmPassword) {",
  "      Alert.alert('Error', 'New passwords do not match');",
  "      return;",
  "    }",
  "    setLoading(true);",
  "    try {",
  "      await api.changePassword(token!, currentPassword, newPassword);",
  "      Alert.alert('Success', 'Password updated successfully');",
  "      setCurrentPassword('');",
  "      setNewPassword('');",
  "      setConfirmPassword('');",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  };",
  "",
  "  const sendBroadcastPush = async (tokens, title, body) => {",
  "    if (tokens.length === 0) return;",
  "    const messages = tokens.map(t => ({",
  "      to: t,",
  "      sound: 'default',",
  "      title: title,",
  "      body: body,",
  "      data: { screen: 'notices' }",
  "    }));",
  "    try {",
  "      await fetch('https://exp.host/--/api/v2/push/send', {",
  "        method: 'POST',",
  "        headers: {",
  "          'Accept': 'application/json',",
  "          'Accept-Encoding': 'gzip, deflate',",
  "          'Content-Type': 'application/json',",
  "        },",
  "        body: JSON.stringify(messages),",
  "      });",
  "    } catch (e) {",
  "      console.error('Failed to send broadcast push:', e);",
  "    }",
  "  };",
  "",
  "  const handleBroadcastNotice = async () => {",
  "    Keyboard.dismiss();",
  "    if (!noticeText.trim()) {",
  "      Alert.alert('Error', 'Please enter a notice message');",
  "      return;",
  "    }",
  "    setNoticeText('');",
  "    setBroadcasting(true);",
  "    try {",
  "      let currentNotices = [];",
  "      try {",
  "        const res = await api.getSetting('notices');",
  "        if (res && res.value) {",
  "          currentNotices = Array.isArray(res.value) ? res.value : [];",
  "        }",
  "      } catch (e) {",
  "        console.log('Initializing first notice record');",
  "      }",
  "",
  "      const newNotice = {",
  "        id: Date.now().toString(),",
  "        message: noticeText.trim(),",
  "        createdAt: new Date().toISOString()",
  "      };",
  "      const updatedNotices = [newNotice, ...currentNotices].slice(0, 50);",
  "",
  "      await api.updateSetting(token!, 'notices', updatedNotices);",
  "",
  "      const users = await api.getUsers(token!);",
  "      const tokens = users",
  "        .filter((u: any) => u.role === 'employee' && u.expoPushToken)",
  "        .map((u: any) => u.expoPushToken);",
  "",
  "      if (tokens.length > 0) {",
  "        await sendBroadcastPush(tokens, 'Store Announcement 📢', noticeText.trim());",
  "      }",
  "",
  "      Alert.alert('Success', 'Notice broadcasted successfully to all staff phones!');",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message || 'Failed to broadcast notice');",
  "    } finally {",
  "      setBroadcasting(false);",
  "    }",
  "  };",
  "",
  "  const redTheme = {",
  "    ...MD3LightTheme,",
  "    colors: {",
  "      ...MD3LightTheme.colors,",
  "      primary: '#D32F2F',",
  "    },",
  "  };",
  "",
  "  return (",
  "    <Provider theme={redTheme}>",
  "      <ScrollView style={styles.screen} contentContainerStyle={styles.container}>",
  "        <Text style={styles.pageTitle}>Admin Settings</Text>",
  "",
  "        <Card style={styles.card}>",
  "          <Card.Title ",
  "            title='Broadcast Store Notice' ",
  "            subtitle='Broadcast real-time push and in-app notice to all staff'",
  "            left={(props) => <MaterialCommunityIcons {...props} name='bullhorn' color='#D32F2F' 
/>}",
  "          />",
  "          <Card.Content>",
  "            <TextInput",
  "              label='Notice Message *'",
  "              value={noticeText}",
  "              onChangeText={setNoticeText}",
  "              mode='outlined'",
  "              multiline",
  "              numberOfLines={4}",
  "              style={{ marginBottom: 12 }}",
  "              placeholder='Type your notice announcement here...'",
  "            />",
  "            <Button",
  "              mode='contained'",
  "              icon='send'",
  "              onPress={handleBroadcastNotice}",
  "              loading={broadcasting}",
  "              disabled={broadcasting}",
  "              buttonColor='#D32F2F'",
  "            >",
  "              Broadcast Notice",
  "            </Button>",
  "          </Card.Content>",
  "        </Card>",
  "",
  "        <Card style={styles.card}>",
  "          <Card.Title ",
  "            title='Showroom Location' ",
  "            subtitle='Configure showroom coordinates for GPS-based attendance'",
  "            left={(props) => <MaterialCommunityIcons {...props} name='map-marker' color='#D32F2F' 
/>}",
  "          />",
  "          <Card.Content>",
  "            <TextInput",
  "              label='Latitude'",
  "              value={lat}",
  "              onChangeText={setLat}",
  "              mode='outlined'",
  "              keyboardType='numeric'",
  "              style={styles.input}",
  "            />",
  "            <TextInput",
  "              label='Longitude'",
  "              value={lng}",
  "              onChangeText={setLng}",
  "              mode='outlined'",
  "              keyboardType='numeric'",
  "              style={styles.input}",
  "            />",
  "            <TextInput",
  "              label='Radius (meters)'",
  "              value={radius}",
  "              onChangeText={setRadius}",
  "              mode='outlined'",
  "              keyboardType='numeric'",
  "              style={styles.input}",
  "            />",
  "            <View style={styles.locationButtons}>",
  "              <Button mode='outlined' onPress={handleUseCurrentLocation} style={styles.locBtn} 
loading={loading} icon='crosshairs-gps'>",
  "                Use Current GPS",
  "              </Button>",
  "              <Button mode='contained' onPress={handleSaveLocation} style={styles.locBtn} 
buttonColor='#D32F2F' icon='content-save'>",
  "                Save Location",
  "              </Button>",
  "            </View>",
  "          </Card.Content>",
  "        </Card>",
  "",
  "        <Card style={styles.card}>",
  "          <Card.Title ",
  "            title='Mark Holiday' ",
  "            subtitle='Set holiday for all employees'",
  "            left={(props) => <MaterialCommunityIcons {...props} name='calendar-star' 
color='#D32F2F' />}",
  "          />",
  "          <Card.Content>",
  "            <TextInput",
  "              label='Date (YYYY-MM-DD)'",
  "              value={holidayDate}",
  "              onChangeText={setHolidayDate}",
  "              mode='outlined'",
  "              style={styles.input}",
  "            />",
  "            <TextInput",
  "              label='Reason for Holiday'",
  "              value={holidayReason}",
  "              onChangeText={setHolidayReason}",
  "              mode='outlined'",
  "              style={styles.input}",
  "            />",
  "            <Button mode='contained' onPress={handleMarkHoliday} buttonColor='#D32F2F' 
icon='calendar-check'>",
  "              Mark Holiday",
  "            </Button>",
  "          </Card.Content>",
  "        </Card>",
  "",
  "        <Card style={styles.card}>",
  "          <Card.Title ",
  "            title='Change Password' ",
  "            subtitle='Update your administrator password'",
  "            left={(props) => <MaterialCommunityIcons {...props} name='lock-reset' color='#D32F2F' 
/>}",
  "          />",
  "          <Card.Content>",
  "            <TextInput",
  "              label='Current Password'",
  "              value={currentPassword}",
  "              onChangeText={setCurrentPassword}",
  "              mode='outlined'",
  "              secureTextEntry",
  "              style={styles.input}",
  "            />",
  "            <TextInput",
  "              label='New Password'",
  "              value={newPassword}",
  "              onChangeText={setNewPassword}",
  "              mode='outlined'",
  "              secureTextEntry",
  "              style={styles.input}",
  "            />",
  "            <TextInput",
  "              label='Confirm New Password'",
  "              value={confirmPassword}",
  "              onChangeText={setConfirmPassword}",
  "              mode='outlined'",
  "              secureTextEntry",
  "              style={styles.input}",
  "            />",
  "            <Button mode='contained' onPress={handleUpdatePassword} buttonColor='#4CAF50' 
icon='shield-check'>",
  "              Update Password",
  "            </Button>",
  "          </Card.Content>",
  "        </Card>",
  "",
  "        <Card style={styles.card}>",
  "          <Card.Title ",
  "            title='App Information' ",
  "            left={(props) => <MaterialCommunityIcons {...props} name='information-outline' 
color='#666' />}",
  "          />",
  "          <Card.Content>",
  "            <View style={styles.infoRow}>",
  "              <MaterialCommunityIcons name='calendar-clock' size={18} color='#666' />",
  "              <Text style={styles.infoText}>Employees must apply leave before 10 PM 
today.</Text>",
  "            </View>",
  "            <View style={styles.infoRow}>",
  "              <MaterialCommunityIcons name='map-marker-radius' size={18} color='#666' />",
  "              <Text style={styles.infoText}>GPS verification works within the set radius of the 
showroom.</Text>",
  "            </View>",
  "            <View style={styles.infoRow}>",
  "              <MaterialCommunityIcons name='star' size={18} color='#666' />",
  "              <Text style={styles.infoText}>Double Bonus: 7 days present OR 6 days present + 
approved leave.</Text>",
  "            </View>",
  "          </Card.Content>",
  "        </Card>",
  "",
  "        <Button mode='contained' onPress={logout} buttonColor='#D32F2F' style={styles.logoutBtn} 
icon='logout'>",
  "          Logout",
  "        </Button>",
  "        <View style={{ height: 40 }} />",
  "      </ScrollView>",
  "    </Provider>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  screen: { flex: 1, backgroundColor: '#f5f5f5' },",
  "  container: { padding: 16 },",
  "  pageTitle: { fontSize: 24, fontWeight: 'bold', color: '#333', marginBottom: 16 },",
  "  card: { marginBottom: 16, backgroundColor: '#fff', elevation: 2 },",
  "  input: { marginBottom: 12 },",
  "  locationButtons: { flexDirection: 'row', justifyContent: 'space-between', gap: 8, marginTop: 4 
},",
  "  locBtn: { flex: 1 },",
  "  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, paddingRight: 12 },",
  "  infoText: { fontSize: 13, color: '#666', marginLeft: 12, flex: 1 },",
  "  logoutBtn: { marginVertical: 12, paddingVertical: 4 },",
  "});"
];

// 7. app/admin/employees.tsx (Fixed Calendar Year bug 2026 for Employees view)
const adminEmployees = [
  "import React, { useState, useEffect, useCallback } from 'react';",
  "import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert, Platform, Keyboard } from 
'react-native';",
  "import { TextInput, Button, Modal, Portal, Provider, Switch, Chip, SegmentedButtons, FAB, Divider 
} from 'react-native-paper';",
  "import { Calendar } from 'react-native-calendars';",
  "import { Picker } from '@expo/vector-icons';",
  "import { MaterialCommunityIcons } from '@expo/vector-icons';",
  "import { useAuth } from '../../src/context/AuthContext';",
  "import { api } from '../../src/services/api';",
  "",
  "const STATUS_COLORS = {",
  "  present: { key: 'present', color: '#4CAF50', selectedDotColor: '#4CAF50' },",
  "  'half-day': { key: 'halfday', color: '#FF9800', selectedDotColor: '#FF9800' },",
  "  absent: { key: 'absent', color: '#F44336', selectedDotColor: '#F44336' },",
  "  leave: { key: 'leave', color: '#2196F3', selectedDotColor: '#2196F3' },",
  "  holiday: { key: 'holiday', color: '#9C27B0', selectedDotColor: '#9C27B0' },",
  "};",
  "",
  "const getISTDate = () => {",
  "  const d = new Date();",
  "  const utc = d.getTime() + (d.getTimezoneOffset() * 60000);",
  "  return new Date(utc + (3600000 * 5.5));",
  "};",
  "",
  "const getISTMonthString = (dateObj) => {",
  "  const d = dateObj || getISTDate();",
  "  return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0');",
  "};",
  "",
  "export default function EmployeesScreen() {",
  "  const { token } = useAuth();",
  "  const [view, setView] = useState('list');",
  "  const [employees, setEmployees] = useState([]);",
  "  const [loading, setLoading] = useState(false);",
  "",
  "  const [showModal, setShowModal] = useState(false);",
  "  const [editingEmployee, setEditingEmployee] = useState(null);",
  "  const [formName, setFormName] = useState('');",
  "  const [formUsername, setFormUsername] = useState('');",
  "  const [formPassword, setFormPassword] = useState('');",
  "  const [formSalary, setFormSalary] = useState('');",
  "  const [formDoubleEnabled, setFormDoubleEnabled] = useState(false);",
  "  ",
  "  const [newEmployeePassword, setNewEmployeePassword] = useState('');",
  "  const [resettingPassword, setResettingPassword] = useState(false);",
  "",
  "  const [selectedEmployee, setSelectedEmployee] = useState('');",
  "  const [selectedMonth, setSelectedMonth] = useState(() => getISTMonthString());",
  "  const [attendanceData, setAttendanceData] = useState({});",
  "  const [markedDates, setMarkedDates] = useState({});",
  "  const [selectedDate, setSelectedDate] = useState('');",
  "  const [showStatusPicker, setShowStatusPicker] = useState(false);",
  "  const [customTime, setCustomTime] = useState('');",
  "",
  "  const fetchEmployees = useCallback(async () => {",
  "    if (!token) return;",
  "    setLoading(true);",
  "    try {",
  "      const data = await api.getUsers(token);",
  "      setEmployees(data);",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message);",
  "    } finally {",
  "      setLoading(false);",
  "    }",
  "  }, [token]);",
  "",
  "  useEffect(() => {",
  "    fetchEmployees();",
  "  }, [fetchEmployees]);",
  "",
  "  const fetchCalendarData = useCallback(async () => {",
  "    if (!token || !selectedEmployee || !selectedMonth) return;",
  "    try {",
  "      const data = await api.getUserMonthAttendance(token, selectedEmployee, selectedMonth);",
  "      const byDate: any = {};",
  "      const marks: any = {};",
  "      ",
  "      for (const record of data) {",
  "        byDate[record.date] = record;",
  "        const statusColor = STATUS_COLORS[record.status];",
  "        if (statusColor) {",
  "          marks[record.date] = {",
  "            selected: true,",
  "            selectedColor: statusColor.color,",
  "          };",
  "        }",
  "      }",
  "      ",
  "      setAttendanceData(byDate);",
  "      setMarkedDates(marks);",
  "    } catch {}",
  "  }, [token, selectedEmployee, selectedMonth]);",
  "",
  "  useEffect(() => {",
  "    if (view === 'calendar') fetchCalendarData();",
  "  }, [view, fetchCalendarData]);",
  "",
  "  const handleCreateOrUpdate = async () => {",
  "    if (!token) return;",
  "    try {",
  "      if (editingEmployee) {",
  "        const updateData: any = {};",
  "        if (formName) updateData.name = formName;",
  "        if (formSalary) updateData.dailySalary = parseFloat(formSalary);",
  "        updateData.doubleEnabled = formDoubleEnabled;",
  "        await api.updateUser(token, editingEmployee._id, updateData);",
  "        Alert.alert('Success', 'Employee updated');",
  "      } else {",
  "        if (!formName || !formUsername || !formPassword || !formSalary) {",
  "          Alert.alert('Error', 'All fields are required');",
  "          return;",
  "        }",
  "        await api.createUser(token, {",
  "          name: formName,",
  "          username: formUsername,",
  "          password: formPassword,",
  "          dailySalary: parseFloat(formSalary),",
  "          role: 'employee',",
  "          doubleEnabled: formDoubleEnabled,",
  "        });",
  "        Alert.alert('Success', 'Employee created');",
  "      }",
  "      resetForm();",
  "      fetchEmployees();",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message);",
  "    }",
  "  };",
  "",
  "  const handleDelete = async (userId) => {",
  "    if (!token) return;",
  "    const doDelete = () => {",
  "      api.deleteUser(token, userId).then(() => {",
  "        fetchEmployees();",
  "      }).catch((e: any) => Alert.alert('Error', e.message));",
  "    };",
  "    if (Platform.OS === 'web') {",
  "      if (confirm('Delete this employee?')) doDelete();",
  "    } else {",
  "      Alert.alert('Confirm', 'Delete this employee?', [",
  "        { text: 'Cancel' },",
  "        { text: 'Delete', style: 'destructive', onPress: doDelete },",
  "      ]);",
  "    }",
  "  };",
  "",
  "  const handleEditEmployee = (emp) => {",
  "    setEditingEmployee(emp);",
  "    setFormName(emp.name);",
  "    setFormUsername(emp.username);",
  "    setFormSalary(String(emp.dailySalary || 0));",
  "    setFormDoubleEnabled(emp.doubleEnabled || false);",
  "    setShowModal(true);",
  "  };",
  "",
  "  const resetForm = () => {",
  "    setShowModal(false);",
  "    setEditingEmployee(null);",
  "    setFormName('');",
  "    setFormUsername('');",
  "    setFormPassword('');",
  "    setFormSalary('');",
  "    setFormDoubleEnabled(false);",
  "    setNewEmployeePassword('');",
  "  };",
  "",
  "  const handleResetEmployeePassword = async () => {",
  "    Keyboard.dismiss();",
  "    if (!token || !editingEmployee) return;",
  "    ",
  "    if (!newEmployeePassword || newEmployeePassword.length < 4) {",
  "      Alert.alert('Error', 'Password must be at least 4 characters');",
  "      return;",
  "    }",
  "    setResettingPassword(true);",
  "    try {",
  "      await api.resetUserPassword(token, editingEmployee._id, newEmployeePassword);",
  "      Alert.alert('Success', 'Password reset successfully for ' + editingEmployee.name);",
  "      setNewEmployeePassword('');",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message || 'Failed to reset password');",
  "    } finally {",
  "      setResettingPassword(false);",
  "    }",
  "  };",
  "",
  "  const handleMarkAttendance = (status) => {",
  "    if (!token || !selectedEmployee || !selectedDate) return;",
  "    ",
  "    if (customTime && !/^([01]\\d|2[0-3]):([0-5]\\d)$/.test(customTime)) {",
  "      Alert.alert('Error', 'Invalid time format. Use HH:mm (e.g., 09:30)');",
  "      return;",
  "    }",
  "    try {",
  "      const payload: any = {",
  "        userId: selectedEmployee,",
  "        date: selectedDate,",
  "        status,",
  "      };",
  "      if (customTime) {",
  "        payload.checkInTime = selectedDate + 'T' + customTime + ':00+05:30';",
  "      }",
  "      await api.markAttendanceManual(token, payload);",
  "      setShowStatusPicker(false);",
  "      setCustomTime('');",
  "      fetchCalendarData();",
  "      Alert.alert('Success', 'Marked as ' + status);",
  "    } catch (e: any) {",
  "      Alert.alert('Error', e.message);",
  "    }",
  "  };",
  "",
  "  const formatCheckInTime = (timestamp) => {",
  "    if (!timestamp) return '';",
  "    return new Date(timestamp).toLocaleTimeString('en-IN', {",
  "      timeZone: 'Asia/Kolkata',",
  "      hour: '2-digit',",
  "      minute: '2-digit',",
  "      hour12: true",
  "    });",
  "  };",
  "",
  "  const renderEmployeeList = () => (",
  "    <ScrollView style={styles.container}>",
  "      <View style={styles.headerCard}>",
  "        <Text style={styles.headerTitle}>Manage Employees</Text>",
  "        <Text style={styles.headerSub}>Total Employees: {employees.length}</Text>",
  "      </View>",
  "      {employees.map((emp) => (",
  "        <View key={emp._id} style={styles.empCard}>",
  "          <View style={styles.empInfo}>",
  "            <View style={styles.empNameRow}>",
  "              <MaterialCommunityIcons name='account' size={20} color='#D32F2F' />",
  "              <Text style={styles.empName}>{emp.name}</Text>",
  "              {emp.doubleEnabled && (",
  "                <View style={styles.doubleBadge}>",
  "                  <Text style={styles.doubleBadgeText}>2x</Text>",
  "                </View>",
  "              )}",
  "            </View>",
  "            <Text style={styles.empMeta}>@{emp.username} • ₹{emp.dailySalary}/day</Text>",
  "          </View>",
  "          <View style={styles.empActions}>",
  "            <TouchableOpacity onPress={() => handleEditEmployee(emp)} style={styles.actionBtn}>",
  "              <MaterialCommunityIcons name='pencil' size={20} color='#D32F2F' />",
  "            </TouchableOpacity>",
  "            <TouchableOpacity onPress={() => handleDelete(emp._id)} style={styles.actionBtn}>",
  "              <MaterialCommunityIcons name='delete' size={20} color='#F44336' />",
  "            </TouchableOpacity>",
  "          </View>",
  "        </View>",
  "      ))}",
  "      <View style={{ height: 80 }} />",
  "    </ScrollView>",
  "  );",
  "",
  "  const renderCalendarView = () => (",
  "    <ScrollView style={styles.container}>",
  "      <View style={styles.headerCard}>",
  "        <Text style={styles.headerTitle}>Manual Attendance</Text>",
  "        <Text style={styles.headerSub}>Select employee and tap any date to mark</Text>",
  "      </View>",
  "      <View style={styles.pickerContainer}>",
  "        <Text style={styles.pickerLabel}>Select Employee</Text>",
  "        <View style={styles.pickerBox}>",
  "          <Picker",
  "            selectedValue={selectedEmployee}",
  "            onValueChange={(val) => setSelectedEmployee(val)}",
  "            style={styles.picker}",
  "          >",
  "            <Picker.Item label='-- Select Employee --' value='' />",
  "            {employees.map((emp) => (",
  "              <Picker.Item key={emp._id} label={emp.name} value={emp._id} />",
  "            ))}",
  "          </Picker>",
  "        </View>",
  "      </View>",
  "      {selectedEmployee ? (",
  "        <>",
  "          <View style={styles.legendRow}>",
  "            {Object.entries(STATUS_COLORS).map(([status, info]) => (",
  "              <View key={status} style={styles.legendItem}>",
  "                <View style={[styles.legendDot, { backgroundColor: info.color }]} />",
  "                <Text style={styles.legendText}>{status}</Text>",
  "              </View>",
  "            ))}",
  "          </View>",
  "          <Calendar",
  "            current={selectedMonth + '-01'}",
  "            markedDates={markedDates}",
  "            onDayPress={(day) => {",
  "              setSelectedDate(day.dateString);",
  "              setCustomTime('');",
  "              setShowStatusPicker(true);",
  "            }}",
  "            onMonthChange={(month) => {",
  "              const m = month.year.toString() + '-' + String(month.month).padStart(2, '0');",
  "              setSelectedMonth(m);",
  "            }}",
  "            theme={{",
  "              selectedDayBackgroundColor: '#D32F2F',",
  "              todayTextColor: '#D32F2F',",
  "              arrowColor: '#D32F2F',",
  "            }}",
  "            style={styles.calendar}",
  "          />",
  "          {selectedDate && attendanceData[selectedDate] && (",
  "            <View style={styles.selectedInfo}>",
  "              <Text style={styles.selectedDate}>{selectedDate}</Text>",
  "              <Chip style={[styles.statusChip, { backgroundColor: 
STATUS_COLORS[attendanceData[selectedDate].status]?.color || '#999' }]}>",
  "                <Text style={{ color: '#fff' 
}}>{attendanceData[selectedDate].status.toUpperCase()}</Text>",
  "              </Chip>",
  "              {attendanceData[selectedDate].checkInTime && (",
  "                <Text style={styles.markedBy}>",
  "                  Check-in: {formatCheckInTime(attendanceData[selectedDate].checkInTime)}",
  "                </Text>",
  "              )}",
  "              {attendanceData[selectedDate].markedBy && (",
  "                <Text style={styles.markedBy}>Marked by: 
{attendanceData[selectedDate].markedBy}</Text>",
  "              )}",
  "            </View>",
  "          )}",
  "        </>",
  "      ) : (",
  "        <View style={styles.emptyState}>",
  "          <MaterialCommunityIcons name='calendar-account' size={48} color='#ccc' />",
  "          <Text style={styles.emptyText}>Select an employee to view calendar</Text>",
  "        </View>",
  "      )}",
  "      <View style={{ height: 80 }} />",
  "    </ScrollView>",
  "  );",
  "",
  "  return (",
  "    <Provider>",
  "      <View style={styles.screen}>",
  "        <View style={styles.segmentContainer}>",
  "          <SegmentedButtons",
  "            value={view}",
  "            onValueChange={setView}",
  "            buttons={[",
  "              { value: 'list', label: 'Employee List', icon: 'account-group' },",
  "              { value: 'calendar', label: 'Manual Attendance', icon: 'calendar-edit' },",
  "            ]}",
  "            style={styles.segmentButtons}",
  "          />",
  "        </View>",
  "        {view === 'list' ? renderEmployeeList() : renderCalendarView()}",
  "        {view === 'list' && (",
  "          <FAB",
  "            icon='plus'",
  "            style={styles.fab}",
  "            onPress={() => {",
  "              resetForm();",
  "              setShowModal(true);",
  "            }}",
  "            label='Add Employee'",
  "          />",
  "        )}",
  "        <Portal>",
  "          <Modal visible={showModal} onDismiss={resetForm} 
contentContainerStyle={styles.modal}>",
  "            <ScrollView>",
  "              <Text style={styles.modalTitle}>",
  "                {editingEmployee ? 'Edit Employee' : 'Add Employee'}",
  "              </Text>",
  "              <TextInput",
  "                label='Full Name *'",
  "                value={formName}",
  "                onChangeText={setFormName}",
  "                style={styles.input}",
  "                mode='outlined'",
  "              />",
  "              {!editingEmployee && (",
  "                <>",
  "                  <TextInput",
  "                    label='Username *'",
  "                    value={formUsername}",
  "                    onChangeText={setFormUsername}",
  "                    style={styles.input}",
  "                    mode='outlined'",
  "                    autoCapitalize='none'",
  "                  />",
  "                  <TextInput",
  "                    label='Password *'",
  "                    value={formPassword}",
  "                    onChangeText={setFormPassword}",
  "                    style={styles.input}",
  "                    mode='outlined'",
  "                    secureTextEntry",
  "                  />",
  "                </>",
  "              )}",
  "              <TextInput",
  "                label='Daily Salary (₹) *'",
  "                value={formSalary}",
  "                onChangeText={setFormSalary}",
  "                style={styles.input}",
  "                mode='outlined'",
  "                keyboardType='numeric'",
  "              />",
  "              <View style={styles.switchRow}>",
  "                <View style={styles.switchInfo}>",
  "                  <Text style={styles.switchLabel}>Double Concept</Text>",
  "                  <Text style={styles.switchDesc}>",
  "                    Extra day salary for full week attendance",
  "                  </Text>",
  "                </View>",
  "                <Switch",
  "                  value={formDoubleEnabled}",
  "                  onValueChange={setFormDoubleEnabled}",
  "                  color='#D32F2F'",
  "                />",
  "              </View>",
  "              {editingEmployee && (",
  "                <>",
  "                  <Divider style={{ marginVertical: 16 }} />",
  "                  <Text style={styles.sectionTitle}>Reset Employee Password</Text>",
  "                  <TextInput",
  "                    label='New Password'",
  "                    value={newEmployeePassword}",
  "                    onChangeText={setNewEmployeePassword}",
  "                    style={styles.input}",
  "                    mode='outlined'",
  "                    secureTextEntry",
  "                  />",
  "                  <Button",
  "                    mode='contained'",
  "                    onPress={handleResetEmployeePassword}",
  "                    loading={resettingPassword}",
  "                    disabled={!newEmployeePassword}",
  "                    buttonColor='#FF9800'",
  "                    style={{ marginBottom: 8 }}",
  "                    icon='lock-reset'",
  "                  >",
  "                    Reset Password",
  "                  </Button>",
  "                </>",
  "              )}",
  "              <View style={styles.modalButtons}>",
  "                <Button mode='outlined' onPress={resetForm} style={[styles.modalBtn, { 
marginRight: 4 }]}>",
  "                  Cancel",
  "                </Button>",
  "                <Button mode='contained' onPress={handleCreateOrUpdate} style={[styles.modalBtn, 
{ marginLeft: 4 }]}>",
  "                  {editingEmployee ? 'Update' : 'Add Employee'}",
  "                </Button>",
  "              </View>",
  "            </ScrollView>",
  "          </Modal>",
  "        </Portal>",
  "        <Portal>",
  "          <Modal visible={showStatusPicker} onDismiss={() => setShowStatusPicker(false)} 
contentContainerStyle={styles.statusModal}>",
  "            <Text style={styles.modalTitle}>Mark Attendance</Text>",
  "            <Text style={styles.statusDate}>{selectedDate}</Text>",
  "            <TextInput",
  "              label='Check-in Time (HH:mm) - Optional'",
  "              value={customTime}",
  "              onChangeText={(text) => {",
  "                let formatted = text.replace(/[^0-9:]/g, '');",
  "                if (formatted.length === 2 && !formatted.includes(':') && customTime.length < 2) 
{",
  "                  formatted = formatted + ':';",
  "                }",
  "                setCustomTime(formatted);",
  "              }}",
  "              placeholder='e.g. 09:00'",
  "              mode='outlined'",
  "              style={{ marginBottom: 16 }}",
  "              maxLength={5}",
  "              keyboardType='numeric'",
  "            />",
  "            {Object.entries(STATUS_COLORS).map(([status, info]) => (",
  "              <TouchableOpacity",
  "                key={status}",
  "                style={[styles.statusOption, { borderLeftColor: info.color }]}",
  "                onPress={() => handleMarkAttendance(status)}",
  "              >",
  "                <View style={[styles.statusDot, { backgroundColor: info.color }]} />",
  "                <Text style={styles.statusText}>{status.charAt(0).toUpperCase() + 
status.slice(1)}</Text>",
  "              </TouchableOpacity>",
  "            ))}",
  "            <Button mode='outlined' onPress={() => setShowStatusPicker(false)} style={{ 
marginTop: 12 }}>",
  "              Cancel",
  "            </Button>",
  "          </Modal>",
  "        </Portal>",
  "      </View>",
  "    </Provider>",
  "  );",
  "}",
  "",
  "const styles = StyleSheet.create({",
  "  screen: { flex: 1, backgroundColor: '#f5f5f5' },",
  "  container: { flex: 1, padding: 16 },",
  "  segmentContainer: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4, backgroundColor: 
'#f5f5f5' },",
  "  segmentButtons: { marginBottom: 4 },",
  "  headerCard: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 12, 
elevation: 2 },",
  "  headerTitle: { fontSize: 22, fontWeight: 'bold', color: '#333' },",
  "  headerSub: { fontSize: 14, color: '#666', marginTop: 4 },",
  "  empCard: { backgroundColor: '#fff', borderRadius: 12, padding: 16, marginBottom: 8, 
flexDirection: 'row', alignItems: 'center', elevation: 1 },",
  "  empInfo: { flex: 1 },",
  "  empNameRow: { flexDirection: 'row', alignItems: 'center' },",
  "  empName: { fontSize: 16, fontWeight: '600', color: '#333', marginLeft: 8, flexShrink: 1 },",
  "  doubleBadge: { backgroundColor: '#E8EAF6', borderRadius: 6, paddingHorizontal: 6, 
paddingVertical: 2, marginLeft: 8, alignItems: 'center', justifyContent: 'center', alignSelf: 
'center', flexShrink: 0 },",
  "  doubleBadgeText: { fontSize: 11, fontWeight: 'bold', color: '#3F51B5', lineHeight: 14, 
includeFontPadding: false, textAlignVertical: 'center' },",
  "  empMeta: { fontSize: 13, color: '#888', marginTop: 4, marginLeft: 28 },",
  "  empActions: { flexDirection: 'row' },",
  "  actionBtn: { padding: 8 },",
  "  pickerContainer: { marginBottom: 12 },",
  "  pickerLabel: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 4 },",
  "  pickerBox: { backgroundColor: '#fff', borderRadius: 8, borderWidth: 1, borderColor: '#ddd' },",
  "  picker: { height: 50 },",
  "  legendRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8, padding: 8, 
backgroundColor: '#fff', borderRadius: 8 },",
  "  legendItem: { flexDirection: 'row', alignItems: 'center' },",
  "  legendDot: { width: 12, height: 12, borderRadius: 6 },",
  "  legendText: { fontSize: 11, color: '#666', textTransform: 'capitalize', marginLeft: 4 },",
  "  calendar: { borderRadius: 12, elevation: 2, marginBottom: 12 },",
  "  selectedInfo: { backgroundColor: '#fff', borderRadius: 12, padding: 16, alignItems: 'center' 
},",
  "  selectedDate: { fontSize: 16, fontWeight: '600', marginBottom: 8 },",
  "  statusChip: { paddingHorizontal: 8, marginBottom: 8 },",
  "  markedBy: { fontSize: 12, color: '#888', marginTop: 4 },",
  "  emptyState: { alignItems: 'center', padding: 40 },",
  "  emptyText: { color: '#999', marginTop: 8, fontSize: 14 },",
  "  fab: { position: 'absolute', right: 16, bottom: 16, backgroundColor: '#D32F2F' },",
  "  modal: { backgroundColor: '#fff', margin: 20, padding: 20, borderRadius: 12, maxHeight: '85%' 
},",
  "  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 16, color: '#333' },",
  "  input: { marginBottom: 12 },",
  "  switchRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f5f5f5', 
borderRadius: 8, padding: 12, marginBottom: 16 },",
  "  switchInfo: { flex: 1 },",
  "  switchLabel: { fontSize: 16, fontWeight: '600', color: '#333' },",
  "  switchDesc: { fontSize: 12, color: '#888', marginTop: 2 },",
  "  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#FF9800', marginBottom: 4 },",
  "  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end' },",
  "  modalBtn: { flex: 1 },",
  "  statusModal: { backgroundColor: '#fff', margin: 20, padding: 20, borderRadius: 12 },",
  "  statusDate: { fontSize: 16, color: '#666', marginBottom: 16, textAlign: 'center' },",
  "  statusOption: { flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 8, 
borderLeftWidth: 4, backgroundColor: '#f9f9f9', marginBottom: 8 },",
  "  statusDot: { width: 16, height: 16, borderRadius: 8, marginRight: 12 },",
  "  statusText: { fontSize: 16, color: '#333', fontWeight: '500' },",
  "});"
];

// Execute all writes
writeFile('app/admin/_layout.tsx', adminLayout);
writeFile('app/employee/_layout.tsx', employeeLayout);
writeFile('app/admin/index.tsx', adminDashboard);
writeFile('app/employee/index.tsx', employeeIndex);
writeFile('app/employee/attendance.tsx', employeeAttendance);
writeFile('app/admin/settings.tsx', adminSettings);
writeFile('app/admin/employees.tsx', adminEmployees);

console.log('SUCCESS: All 7 files written perfectly without any shell syntax errors!');
